[tox]
envlist = py312
skip_missing_interpreters = true
isolated_build = true

[testenv]
deps =
    pytest
    pytest-cov
    pytest-django
    coverage
    django
    djangorestframework
    -r{toxinidir}/requirements-test.txt

commands =
    pytest --cov=backend --cov=courts --cov=accounts --cov=video_hearings \
           --cov-report=term-missing \
           tests/
setenv =
    DJANGO_SETTINGS_MODULE=settings.test

    PYTHONPATH = {toxinidir}
    APP_ENV=test