# Generated by Django 6.0.3 on 2026-03-06 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("courts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "hearing_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("arraignment", "Arraignment"),
                            ("bail", "Bail Hearing"),
                            ("bail_application", "Bail Application"),
                            ("bail_variation", "Bail Variation"),
                            ("case_management", "Case Management Hearing"),
                            ("plea", "Plea Hearing"),
                            ("ptph", "Plea and Trial Preparation Hearing"),
                            ("trial", "Trial"),
                            ("sentencing", "Sentencing Hearing"),
                            ("committal", "Committal for Sentence"),
                            ("appeal", "Appeal Hearing"),
                            ("mention", "Mention Hearing"),
                            ("ptr", "Pre-Trial Review"),
                            ("directions", "Directions Hearing"),
                            ("case_stated", "Case Stated"),
                            ("confiscation", "Confiscation Hearing"),
                            ("breach", "Breach Hearing"),
                            ("review", "Review Hearing"),
                            ("remand", "Remand Hearing"),
                            ("extradition", "Extradition Hearing"),
                            ("first_hearing", "First Hearing"),
                            ("mode_of_trial", "Mode of Trial Hearing"),
                            ("allocation", "Allocation Hearing"),
                            ("sending_for_trial", "Sending for Trial"),
                            ("youth_court", "Youth Court Hearing"),
                            ("civil_trial", "Civil Trial"),
                            ("civil_ccmc", "Civil Case Management Conference"),
                            ("interim", "Interim Hearing"),
                            ("summary_judgment", "Summary Judgment Hearing"),
                            ("injunction", "Injunction Hearing"),
                            ("possession", "Possession Hearing"),
                            ("small_claims", "Small Claims Hearing"),
                            ("fast_track_trial", "Fast Track Trial"),
                            ("multi_track_trial", "Multi-Track Trial"),
                            ("disposal", "Disposal Hearing"),
                            ("pre_trial_check", "Pre-Trial Check"),
                            ("costs", "Costs Hearing"),
                            ("assessment", "Damages Assessment"),
                            ("acknowledgment", "Acknowledgment of Service Hearing"),
                            ("first_directions", "First Directions Appointment"),
                            ("fdr", "Financial Dispute Resolution"),
                            ("financial_final", "Final Financial Hearing"),
                            ("child_arrangements", "Child Arrangements Hearing"),
                            ("cafcass", "CAFCASS Meeting"),
                            ("care_order", "Care Order Hearing"),
                            ("supervision_order", "Supervision Order Hearing"),
                            ("adoption", "Adoption Hearing"),
                            (
                                "emergency_protection",
                                "Emergency Protection Order Hearing",
                            ),
                            ("contact", "Contact Hearing"),
                            ("fact_finding", "Fact Finding Hearing"),
                            ("issues_resolution", "Issues Resolution Hearing"),
                            ("dispute_resolution", "Dispute Resolution Appointment"),
                            (
                                "case_management_family",
                                "Case Management Hearing (Family)",
                            ),
                            ("tribunal_first", "First Tier Tribunal"),
                            ("tribunal_upper", "Upper Tribunal"),
                            ("tribunal_cm", "Tribunal Case Management"),
                            ("employment", "Employment Tribunal"),
                            ("immigration", "Immigration Hearing"),
                            ("social_security", "Social Security Appeal"),
                            ("mental_health", "Mental Health Tribunal"),
                            ("sen", "Special Educational Needs Tribunal"),
                            ("lands", "Lands Tribunal"),
                            ("tax", "Tax Tribunal"),
                            (
                                "ptph_crown",
                                "Plea and Trial Preparation Hearing (Crown)",
                            ),
                            ("pcmh", "Pre-Trial and Case Management Hearing"),
                            ("ground_rules", "Ground Rules Hearing"),
                            ("vulnerable_witness", "Vulnerable Witness Hearing"),
                            ("special_measures", "Special Measures Hearing"),
                            ("chancery", "Chancery Division Hearing"),
                            ("queens_bench", "Queen's Bench Division Hearing"),
                            ("family_division", "Family Division Hearing"),
                            ("administrative", "Administrative Court Hearing"),
                            ("commercial", "Commercial Court Hearing"),
                            ("tcc", "Technology & Construction Court Hearing"),
                            ("admiralty", "Admiralty Court Hearing"),
                            ("coa_civil", "Court of Appeal (Civil Division)"),
                            ("coa_criminal", "Court of Appeal (Criminal Division)"),
                            ("coa_permission", "Permission to Appeal Hearing"),
                            ("supreme_court", "UK Supreme Court Hearing"),
                            ("inquest", "Inquest Hearing"),
                            ("coroners", "Coroner's Court Hearing"),
                            ("court_martial", "Court Martial"),
                            ("ecclesiastical", "Ecclesiastical Court Hearing"),
                            ("charging_order", "Charging Order Hearing"),
                            ("attachment_earnings", "Attachment of Earnings Hearing"),
                            ("third_party_debt", "Third Party Debt Order Hearing"),
                            ("committal_enforcement", "Committal for Non-Payment"),
                            ("bailiff", "Bailiff Hearing"),
                            ("mediation", "Mediation Appointment"),
                            ("arbitration", "Arbitration Hearing"),
                            ("early_neutral", "Early Neutral Evaluation"),
                            ("hybrid", "Hybrid Hearing"),
                        ],
                        default="hybrid",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("recessed", "Recessed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=200)),
                ("session_url", models.URLField(blank=True)),
                ("recording_url", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hearings",
                        to="cases.case",
                    ),
                ),
                (
                    "courtroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courts.courtroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="HearingDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("motion", "Motion"),
                            ("evidence", "Evidence"),
                            ("transcript", "Transcript"),
                            ("order", "Order"),
                            ("exhibit", "Exhibit"),
                            ("warrant", "Warrant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="hearing_docs/%Y/%m/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("is_sealed", models.BooleanField(default=False)),
                ("admitted", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hearing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="video_hearings.hearing",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HearingParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("defendant", "Defendant"),
                            ("prosecutor", "Prosecutor"),
                            ("claimant", "Claimant"),
                            ("respondent", "Respondent"),
                            ("defence_counsel", "Defence Counsel"),
                            ("prosecution_counsel", "Prosecution Counsel"),
                            ("claimant_counsel", "Claimant Counsel"),
                            ("solicitor", "Solicitor"),
                            ("judge", "Judge"),
                            ("magistrate", "Magistrate"),
                            ("clerk", "Court Clerk"),
                            ("usher", "Court Usher"),
                            ("juror", "Juror"),
                            ("witness", "Witness"),
                            ("interpreter", "Interpreter"),
                            ("public", "Public"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("join_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("reconnecting", "Reconnecting"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hearing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="video_hearings.hearing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="hearing",
            index=models.Index(
                fields=["status", "scheduled_at"], name="video_heari_status_be605c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hearing",
            index=models.Index(
                fields=["case", "status"], name="video_heari_case_id_836959_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hearingdocument",
            index=models.Index(
                fields=["hearing", "doc_type"], name="video_heari_hearing_09182d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hearingdocument",
            index=models.Index(
                fields=["uploaded_at"], name="video_heari_uploade_855e7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hearingparticipant",
            index=models.Index(
                fields=["join_token"], name="video_heari_join_to_575fb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hearingparticipant",
            index=models.Index(
                fields=["connection_status"], name="video_heari_connect_3271a5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hearingparticipant",
            unique_together={("hearing", "user", "role")},
        ),
    ]
